version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/aadi-frontend/HCC-Coding-CodeDeploy
    overwrite: yes

file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/aadi-frontend/HCC-Coding-CodeDeploy
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/fix_permissions.sh
      timeout: 600
      runas: ubuntu

  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu


  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ubuntu
