type ProfileType = "Analyst" | "Provider"

export interface UserTypes {
    id: number
    Fname: string
    Lname: string
    email: string
    password: string
    profile_type: ProfileType | number | string
}

export enum PrevisitTab {
    Pending = "pending",
    Draft = "draft",
    Review = "review",
    ProviderReview = "provider-review"
}
export enum PENDINGSTATUS {
    PENDINGSTATUSSTATUS = "Pending",
    DOCRETRIEVAL = "Doc retrieval",
    ERROR = "Error",
}
export enum DRAFTSTATUS {
    PROCESSING = "Processing",
    QUEUE = "In Queue",
    ERROR = "Error",
}
export enum USERTYPES {
    PROVIDER = "Provider",
    ANALYST = "Analyst"
}
export enum PROGRESSNOTESTATUS {
    RFR = "RFR",
    UNASSIGNED = "Unsigned",
    PENDING = "Pending",
    ACTIVE = "Active"
}
export enum CODINGREVIEWSTATUS {
    RFR = "RFR",
    ACTIVE = "Active"
}
export enum CODINGAPPROVEDSTATUS {
    PENDING = "pending",
    ERROR = "Error",
    CREATED = "Created"
}
export enum REVIEWSTATUS {
    RFR = "RFR",
    INPROGRESS = "In Progress",
    HOLD = "On Hold",
    ADDITIONAL = "Additional Review",
    DOCUMENT = "Document Missing"
}
export enum ChartTypeEnum {
    PROVIDER_REVIEW = "provider-review",
    REVIEW = "review",
    MANUAL = "manual",
    POSTREVIEW = "postReview",
    CODINGREVIEW = "codingReview",
}


export interface MemberProfile {
    id: string
    fname: string
    lname: string
    insurance1: string
    subscriberId1: string
    insurance2?: string
    subscriberId2?: string
    pcpId?: number
    dob?: string
    address: string
    city: string
    state: string
    zip: string
    createdOn: string
    updatedOn: string
}

export interface Reference {
    id: string
    title: string
    type: string
    dated: string
    pdfUrl: string
}

export interface HCCEntry {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    code: any
    id: string
    condition: string
    isExpanded: boolean
    references: Reference[]
    note?: string
    status: "pending" | "accepted" | "rejected"
    pNote?: string
}

/* Pending Data */
export type PrevisitDataTypes = {
    chartId: string;
    mID?: string;
    dos: string; // Date of Service
    memberId: string;
    firstName: string;
    lastName: string;
    dob: string; // Date of Birth
    pcp: string; // Primary Care Physician
    facility: string;
    insurance: string;
    status: PENDINGSTATUS;
    assignTo: string;
};
export const PrevisitData: PrevisitDataTypes[] = [
    {
        chartId: "CH12345",
        dos: "01-10-2024",
        memberId: "M001",
        firstName: "John",
        lastName: "Doe",
        dob: "05-15-1990",
        pcp: "Dr. Smith",
        facility: "ABC Clinic",
        insurance: "Blue Shield",
        status: PENDINGSTATUS.PENDINGSTATUSSTATUS,
        assignTo: "Admin1",
    },
    {
        chartId: "CH12346",
        dos: "01-12-2024",
        memberId: "M002",
        firstName: "Jane",
        lastName: "Doe",
        dob: "08-21-1985",
        pcp: "Dr. Williams",
        facility: "XYZ Hospital",
        insurance: "United Health",
        status: PENDINGSTATUS.DOCRETRIEVAL,
        assignTo: "Admin2",
    },
    {
        chartId: "CH12347",
        dos: "02-05-2024",
        memberId: "M003",
        firstName: "Alice",
        lastName: "Brown",
        dob: "02-10-1993",
        pcp: "Dr. Carter",
        facility: "DEF Clinic",
        insurance: "Aetna",
        status: PENDINGSTATUS.ERROR,
        assignTo: "Admin3",
    },
    {
        chartId: "CH12348",
        dos: "02-10-2024",
        memberId: "M004",
        firstName: "Bob",
        lastName: "Smith",
        dob: "07-19-1988",
        pcp: "Dr. Jones",
        facility: "LMN Health Center",
        insurance: "Cigna",
        status: PENDINGSTATUS.PENDINGSTATUSSTATUS,
        assignTo: "Admin4",
    },
    {
        chartId: "CH12349",
        dos: "03-03-2024",
        memberId: "M005",
        firstName: "Charlie",
        lastName: "Davis",
        dob: "04-11-1992",
        pcp: "Dr. Adams",
        facility: "OPQ Medical",
        insurance: "Blue Shield",
        status: PENDINGSTATUS.DOCRETRIEVAL,
        assignTo: "Admin1",
    },
    {
        chartId: "CH12350",
        dos: "03-15-2024",
        memberId: "M006",
        firstName: "David",
        lastName: "Clark",
        dob: "06-30-1980",
        pcp: "Dr. Scott",
        facility: "RST Hospital",
        insurance: "United Health",
        status: PENDINGSTATUS.ERROR,
        assignTo: "Admin2",
    },
    {
        chartId: "CH12351",
        dos: "04-05-2024",
        memberId: "M007",
        firstName: "Eve",
        lastName: "Wilson",
        dob: "11-25-1995",
        pcp: "Dr. Lewis",
        facility: "XYZ Health",
        insurance: "Aetna",
        status: PENDINGSTATUS.PENDINGSTATUSSTATUS,
        assignTo: "Admin3",
    },
    {
        chartId: "CH12352",
        dos: "04-10-2024",
        memberId: "M008",
        firstName: "Frank",
        lastName: "Miller",
        dob: "12-18-1977",
        pcp: "Dr. Hall",
        facility: "QRS Clinic",
        insurance: "Cigna",
        status: PENDINGSTATUS.DOCRETRIEVAL,
        assignTo: "Admin4",
    },
    {
        chartId: "CH12353",
        dos: "05-01-2024",
        memberId: "M009",
        firstName: "Grace",
        lastName: "White",
        dob: "03-09-1991",
        pcp: "Dr. Thompson",
        facility: "LMN Hospital",
        insurance: "Blue Shield",
        status: PENDINGSTATUS.ERROR,
        assignTo: "Admin1",
    },
    {
        chartId: "CH12354",
        dos: "05-15-2024",
        memberId: "M010",
        firstName: "Henry",
        lastName: "Moore",
        dob: "09-22-1983",
        pcp: "Dr. Lopez",
        facility: "ABC Health",
        insurance: "United Health",
        status: PENDINGSTATUS.PENDINGSTATUSSTATUS,
        assignTo: "Admin2",
    },
    {
        chartId: "CH12355",
        dos: "06-01-2024",
        memberId: "M011",
        firstName: "Ivy",
        lastName: "Anderson",
        dob: "07-05-1997",
        pcp: "Dr. Nelson",
        facility: "XYZ Clinic",
        insurance: "Aetna",
        status: PENDINGSTATUS.DOCRETRIEVAL,
        assignTo: "Admin3",
    },
    {
        chartId: "CH12356",
        dos: "06-20-2024",
        memberId: "M012",
        firstName: "Jack",
        lastName: "Thomas",
        dob: "10-10-1986",
        pcp: "Dr. Wright",
        facility: "DEF Medical",
        insurance: "Cigna",
        status: PENDINGSTATUS.ERROR,
        assignTo: "Admin4",
    },
    {
        chartId: "CH12357",
        dos: "07-10-2024",
        memberId: "M013",
        firstName: "Kelly",
        lastName: "Taylor",
        dob: "01-14-1994",
        pcp: "Dr. King",
        facility: "QRS Hospital",
        insurance: "Blue Shield",
        status: PENDINGSTATUS.PENDINGSTATUSSTATUS,
        assignTo: "Admin1",
    },
    {
        chartId: "CH12358",
        dos: "07-25-2024",
        memberId: "M014",
        firstName: "Liam",
        lastName: "Harris",
        dob: "12-30-1989",
        pcp: "Dr. Martinez",
        facility: "RST Health",
        insurance: "United Health",
        status: PENDINGSTATUS.DOCRETRIEVAL,
        assignTo: "Admin2",
    },
    {
        chartId: "CH12359",
        dos: "08-05-2024",
        memberId: "M015",
        firstName: "Mia",
        lastName: "Young",
        dob: "06-21-1990",
        pcp: "Dr. Allen",
        facility: "LMN Clinic",
        insurance: "Aetna",
        status: PENDINGSTATUS.ERROR,
        assignTo: "Admin3",
    },
    {
        chartId: "CH12360",
        dos: "08-20-2024",
        memberId: "M016",
        firstName: "Nathan",
        lastName: "Lee",
        dob: "03-17-1982",
        pcp: "Dr. Perez",
        facility: "OPQ Hospital",
        insurance: "Cigna",
        status: PENDINGSTATUS.PENDINGSTATUSSTATUS,
        assignTo: "Admin4",
    },
];

/* followup data */
export type FollowupData = {
    chartId: string;
    firstName: string;
    lastName: string;
    dos: string; // Date of Service
    pcp: string; // Primary Care Physician
    facility: string;
    insurance: string;
    newSugg: number;
    carryForward: number;
    status: PROGRESSNOTESTATUS;
    assignTo: string;
};

export const followupData: FollowupData[] = [
    {
        chartId: "1001",
        firstName: "John",
        lastName: "Doe",
        dos: "02-10-2024",
        pcp: "Dr. Smith",
        facility: "ABC Hospital",
        insurance: "Medicare",
        newSugg: 2,
        carryForward: 1,
        status: PROGRESSNOTESTATUS.ACTIVE,
        assignTo: "Dr. Adams"
    },
    {
        chartId: "1002",
        firstName: "Jane",
        lastName: "Smith",
        dos: "02-11-2024",
        pcp: "Dr. Brown",
        facility: "XYZ Clinic",
        insurance: "Blue Cross",
        newSugg: 1,
        carryForward: 3,
        status: PROGRESSNOTESTATUS.PENDING,
        assignTo: "Dr. White"
    },
    {
        chartId: "1003",
        firstName: "Michael",
        lastName: "Johnson",
        dos: "02-12-2024",
        pcp: "Dr. Green",
        facility: "LMN Medical Center",
        insurance: "Aetna",
        newSugg: 4,
        carryForward: 0,
        status: PROGRESSNOTESTATUS.RFR,
        assignTo: "Dr. Adams"
    },
    {
        chartId: "1004",
        firstName: "Alice",
        lastName: "Brown",
        dos: "02-13-2024",
        pcp: "Dr. Taylor",
        facility: "PQR Hospital",
        insurance: "Cigna",
        newSugg: 3,
        carryForward: 2,
        status: PROGRESSNOTESTATUS.UNASSIGNED,
        assignTo: "Dr. Clark"
    },
    {
        chartId: "1005",
        firstName: "Robert",
        lastName: "Williams",
        dos: "02-14-2024",
        pcp: "Dr. Adams",
        facility: "DEF Clinic",
        insurance: "UnitedHealthcare",
        newSugg: 2,
        carryForward: 1,
        status: PROGRESSNOTESTATUS.ACTIVE,
        assignTo: "Dr. Lewis"
    },
    {
        chartId: "1006",
        firstName: "Emily",
        lastName: "Davis",
        dos: "02-15-2024",
        pcp: "Dr. Harris",
        facility: "STU Medical Center",
        insurance: "Humana",
        newSugg: 1,
        carryForward: 3,
        status: PROGRESSNOTESTATUS.PENDING,
        assignTo: "Dr. Nelson"
    },
    {
        chartId: "1007",
        firstName: "Daniel",
        lastName: "Martinez",
        dos: "02-16-2024",
        pcp: "Dr. Lee",
        facility: "JKL Hospital",
        insurance: "Aetna",
        newSugg: 3,
        carryForward: 2,
        status: PROGRESSNOTESTATUS.RFR,
        assignTo: "Dr. Cooper"
    },
    {
        chartId: "1008",
        firstName: "Sophia",
        lastName: "Hernandez",
        dos: "02-17-2024",
        pcp: "Dr. White",
        facility: "MNO Clinic",
        insurance: "Blue Cross",
        newSugg: 4,
        carryForward: 0,
        status: PROGRESSNOTESTATUS.UNASSIGNED,
        assignTo: "Dr. Parker"
    },
    {
        chartId: "1009",
        firstName: "James",
        lastName: "Lopez",
        dos: "02-18-2024",
        pcp: "Dr. Moore",
        facility: "GHI Medical Center",
        insurance: "Cigna",
        newSugg: 2,
        carryForward: 3,
        status: PROGRESSNOTESTATUS.ACTIVE,
        assignTo: "Dr. Hall"
    },
    {
        chartId: "1010",
        firstName: "Olivia",
        lastName: "Gonzalez",
        dos: "02-19-2024",
        pcp: "Dr. Scott",
        facility: "XYZ Hospital",
        insurance: "Medicare",
        newSugg: 1,
        carryForward: 2,
        status: PROGRESSNOTESTATUS.PENDING,
        assignTo: "Dr. Edwards"
    },
    {
        chartId: "1011",
        firstName: "William",
        lastName: "Perez",
        dos: "02-20-2024",
        pcp: "Dr. Thompson",
        facility: "JKL Clinic",
        insurance: "Aetna",
        newSugg: 3,
        carryForward: 1,
        status: PROGRESSNOTESTATUS.RFR,
        assignTo: "Dr. Russell"
    },
    {
        chartId: "1012",
        firstName: "Isabella",
        lastName: "Smith",
        dos: "02-21-2024",
        pcp: "Dr. Martinez",
        facility: "LMN Medical Center",
        insurance: "Humana",
        newSugg: 2,
        carryForward: 0,
        status: PROGRESSNOTESTATUS.UNASSIGNED,
        assignTo: "Dr. Bennett"
    },
    {
        chartId: "1013",
        firstName: "Alexander",
        lastName: "Garcia",
        dos: "02-22-2024",
        pcp: "Dr. Anderson",
        facility: "ABC Hospital",
        insurance: "UnitedHealthcare",
        newSugg: 4,
        carryForward: 3,
        status: PROGRESSNOTESTATUS.ACTIVE,
        assignTo: "Dr. Phillips"
    },
    {
        chartId: "1014",
        firstName: "Alice",
        lastName: "Brown",
        dos: "02-14-2024",
        pcp: "Dr. Carter",
        facility: "Sunrise Clinic",
        insurance: "Medicare",
        newSugg: 2,
        carryForward: 1,
        status: PROGRESSNOTESTATUS.ACTIVE,
        assignTo: "Dr. Evans"
    },
    {
        chartId: "1015",
        firstName: "Bob",
        lastName: "Davis",
        dos: "02-15-2024",
        pcp: "Dr. Harris",
        facility: "Green Valley Hospital",
        insurance: "Aetna",
        newSugg: 1,
        carryForward: 0,
        status: PROGRESSNOTESTATUS.PENDING,
        assignTo: "Dr. Johnson"
    },
    {
        chartId: "1016",
        firstName: "Charlie",
        lastName: "Evans",
        dos: "02-16-2024",
        pcp: "Dr. Lopez",
        facility: "Central Medical",
        insurance: "Cigna",
        newSugg: 3,
        carryForward: 2,
        status: PROGRESSNOTESTATUS.RFR,
        assignTo: "Dr. Adams"
    },
    {
        chartId: "1017",
        firstName: "Diana",
        lastName: "Foster",
        dos: "02-17-2024",
        pcp: "Dr. Miller",
        facility: "Blue Ridge Hospital",
        insurance: "UnitedHealth",
        newSugg: 0,
        carryForward: 4,
        status: PROGRESSNOTESTATUS.UNASSIGNED,
        assignTo: "Dr. White"
    },
    {
        chartId: "1018",
        firstName: "Edward",
        lastName: "Garcia",
        dos: "02-18-2024",
        pcp: "Dr. Nelson",
        facility: "Westwood Clinic",
        insurance: "Humana",
        newSugg: 2,
        carryForward: 1,
        status: PROGRESSNOTESTATUS.ACTIVE,
        assignTo: "Dr. Clark"
    },
    {
        chartId: "1019",
        firstName: "Fiona",
        lastName: "Harris",
        dos: "02-19-2024",
        pcp: "Dr. Parker",
        facility: "Lakeview Medical",
        insurance: "Blue Cross",
        newSugg: 1,
        carryForward: 3,
        status: PROGRESSNOTESTATUS.PENDING,
        assignTo: "Dr. Brown"
    },
    {
        chartId: "1020",
        firstName: "George",
        lastName: "Irwin",
        dos: "02-20-2024",
        pcp: "Dr. Roberts",
        facility: "Evergreen Hospital",
        insurance: "Aetna",
        newSugg: 4,
        carryForward: 0,
        status: PROGRESSNOTESTATUS.RFR,
        assignTo: "Dr. Adams"
    },
    {
        chartId: "1021",
        firstName: "Hannah",
        lastName: "Jackson",
        dos: "02-21-2024",
        pcp: "Dr. Sanchez",
        facility: "Mountain View Clinic",
        insurance: "Cigna",
        newSugg: 3,
        carryForward: 2,
        status: PROGRESSNOTESTATUS.ACTIVE,
        assignTo: "Dr. Carter"
    },
    {
        chartId: "1022",
        firstName: "Ian",
        lastName: "Kennedy",
        dos: "02-22-2024",
        pcp: "Dr. Wilson",
        facility: "Sunset Medical Center",
        insurance: "Humana",
        newSugg: 1,
        carryForward: 1,
        status: PROGRESSNOTESTATUS.UNASSIGNED,
        assignTo: "Dr. Harris"
    },
    {
        chartId: "1023",
        firstName: "Julia",
        lastName: "Lopez",
        dos: "02-23-2024",
        pcp: "Dr. Adams",
        facility: "Pinehill Hospital",
        insurance: "Medicare",
        newSugg: 2,
        carryForward: 0,
        status: PROGRESSNOTESTATUS.PENDING,
        assignTo: "Dr. Miller"
    },
    {
        chartId: "1024",
        firstName: "Kevin",
        lastName: "Martinez",
        dos: "02-24-2024",
        pcp: "Dr. Thompson",
        facility: "Grandview Medical",
        insurance: "UnitedHealth",
        newSugg: 0,
        carryForward: 2,
        status: PROGRESSNOTESTATUS.ACTIVE,
        assignTo: "Dr. Nelson"
    },
    {
        chartId: "1025",
        firstName: "Liam",
        lastName: "Nelson",
        dos: "02-25-2024",
        pcp: "Dr. Reed",
        facility: "Springfield Clinic",
        insurance: "Aetna",
        newSugg: 3,
        carryForward: 1,
        status: PROGRESSNOTESTATUS.RFR,
        assignTo: "Dr. White"
    },
    {
        chartId: "1026",
        firstName: "Mia",
        lastName: "Owens",
        dos: "02-26-2024",
        pcp: "Dr. Clark",
        facility: "Seaside Hospital",
        insurance: "Cigna",
        newSugg: 1,
        carryForward: 0,
        status: PROGRESSNOTESTATUS.UNASSIGNED,
        assignTo: "Dr. Adams"
    },
    {
        chartId: "1027",
        firstName: "Noah",
        lastName: "Perez",
        dos: "02-27-2024",
        pcp: "Dr. Allen",
        facility: "Riverside Medical",
        insurance: "Blue Cross",
        newSugg: 4,
        carryForward: 3,
        status: PROGRESSNOTESTATUS.PENDING,
        assignTo: "Dr. Roberts"
    },
    {
        chartId: "1028",
        firstName: "Olivia",
        lastName: "Quinn",
        dos: "02-28-2024",
        pcp: "Dr. Brooks",
        facility: "Valley Hospital",
        insurance: "Medicare",
        newSugg: 2,
        carryForward: 1,
        status: PROGRESSNOTESTATUS.ACTIVE,
        assignTo: "Dr. Lopez"
    }
];

/* coding review*/
export type CodingReviewTypes = {
    chartId: string;
    firstName: string;
    lastName: string;
    dos: string; // Date of Service
    pcp: string; // Primary Care Physician
    facility: string;
    insurance: string;
    DXCodes: number;
    CPTCodes: number;
    status: CODINGREVIEWSTATUS
};
export const codingReviewData: CodingReviewTypes[] = [
    {
        chartId: "CH001",
        firstName: "John",
        lastName: "Doe",
        dos: "02-20-2024",
        pcp: "Dr. Smith",
        facility: "City Hospital",
        insurance: "Blue Cross",
        DXCodes: 5,
        CPTCodes: 3,
        status: CODINGREVIEWSTATUS.RFR,
    },
    {
        chartId: "CH002",
        firstName: "Jane",
        lastName: "Doe",
        dos: "02-21-2024",
        pcp: "Dr. Brown",
        facility: "General Clinic",
        insurance: "United Healthcare",
        DXCodes: 4,
        CPTCodes: 2,
        status: CODINGREVIEWSTATUS.ACTIVE,
    },
    {
        chartId: "CH003",
        firstName: "Alice",
        lastName: "Johnson",
        dos: "02-22-2024",
        pcp: "Dr. Taylor",
        facility: "Downtown Medical",
        insurance: "Aetna",
        DXCodes: 6,
        CPTCodes: 4,
        status: CODINGREVIEWSTATUS.RFR,
    },
    {
        chartId: "CH004",
        firstName: "Bob",
        lastName: "Williams",
        dos: "02-23-2024",
        pcp: "Dr. White",
        facility: "City Hospital",
        insurance: "Cigna",
        DXCodes: 3,
        CPTCodes: 5,
        status: CODINGREVIEWSTATUS.ACTIVE,
    },
    {
        chartId: "CH005",
        firstName: "Emily",
        lastName: "Davis",
        dos: "02-24-2024",
        pcp: "Dr. Adams",
        facility: "General Clinic",
        insurance: "Medicare",
        DXCodes: 5,
        CPTCodes: 3,
        status: CODINGREVIEWSTATUS.RFR,
    },
    {
        chartId: "CH006",
        firstName: "Michael",
        lastName: "Miller",
        dos: "02-25-2024",
        pcp: "Dr. Green",
        facility: "Downtown Medical",
        insurance: "Medicaid",
        DXCodes: 4,
        CPTCodes: 2,
        status: CODINGREVIEWSTATUS.ACTIVE,
    },
    {
        chartId: "CH007",
        firstName: "Sarah",
        lastName: "Wilson",
        dos: "02-26-2024",
        pcp: "Dr. Hall",
        facility: "City Hospital",
        insurance: "Aetna",
        DXCodes: 6,
        CPTCodes: 4,
        status: CODINGREVIEWSTATUS.RFR,
    },
    {
        chartId: "CH008",
        firstName: "David",
        lastName: "Martinez",
        dos: "02-27-2024",
        pcp: "Dr. Lopez",
        facility: "General Clinic",
        insurance: "Cigna",
        DXCodes: 3,
        CPTCodes: 5,
        status: CODINGREVIEWSTATUS.ACTIVE,
    },
    {
        chartId: "CH009",
        firstName: "Laura",
        lastName: "Anderson",
        dos: "02-28-2024",
        pcp: "Dr. Scott",
        facility: "Downtown Medical",
        insurance: "Blue Cross",
        DXCodes: 5,
        CPTCodes: 3,
        status: CODINGREVIEWSTATUS.RFR,
    },
    {
        chartId: "CH010",
        firstName: "James",
        lastName: "Thomas",
        dos: "02-29-2024",
        pcp: "Dr. Baker",
        facility: "City Hospital",
        insurance: "United Healthcare",
        DXCodes: 4,
        CPTCodes: 2,
        status: CODINGREVIEWSTATUS.ACTIVE,
    },
    {
        chartId: "CHART016",
        firstName: "Emma",
        lastName: "Clark",
        dos: "02-16-2024",
        pcp: "Dr. Daniel Robinson",
        facility: "UCLA Medical Center",
        insurance: "Cigna",
        DXCodes: 2,
        CPTCodes: 4,
        status: CODINGREVIEWSTATUS.RFR,
    },
    {
        chartId: "CHART017",
        firstName: "Mason",
        lastName: "Lewis",
        dos: "02-17-2024",
        pcp: "Dr. Kimberly Adams",
        facility: "Mount Sinai Hospital",
        insurance: "Aetna",
        DXCodes: 3,
        CPTCodes: 2,
        status: CODINGREVIEWSTATUS.ACTIVE,
    },
    {
        chartId: "CHART018",
        firstName: "Lucas",
        lastName: "Walker",
        dos: "02-18-2024",
        pcp: "Dr. Brian Carter",
        facility: "Stanford Health Care",
        insurance: "Medicaid",
        DXCodes: 5,
        CPTCodes: 3,
        status: CODINGREVIEWSTATUS.RFR,
    },
    {
        chartId: "CHART019",
        firstName: "Charlotte",
        lastName: "Hall",
        dos: "02-19-2024",
        pcp: "Dr. Victoria King",
        facility: "NewYork-Presbyterian Hospital",
        insurance: "Humana",
        DXCodes: 4,
        CPTCodes: 5,
        status: CODINGREVIEWSTATUS.ACTIVE,
    },
    {
        chartId: "CHART020",
        firstName: "Ethan",
        lastName: "Allen",
        dos: "02-20-2024",
        pcp: "Dr. Henry Wright",
        facility: "Mayo Clinic",
        insurance: "UnitedHealthcare",
        DXCodes: 2,
        CPTCodes: 1,
        status: CODINGREVIEWSTATUS.RFR,
    },
    {
        chartId: "CHART021",
        firstName: "Amelia",
        lastName: "Young",
        dos: "02-21-2024",
        pcp: "Dr. Olivia Green",
        facility: "Massachusetts General Hospital",
        insurance: "Blue Cross Blue Shield",
        DXCodes: 6,
        CPTCodes: 3,
        status: CODINGREVIEWSTATUS.ACTIVE,
    },
    {
        chartId: "CHART022",
        firstName: "Benjamin",
        lastName: "King",
        dos: "02-22-2024",
        pcp: "Dr. William Scott",
        facility: "Cedars-Sinai Medical Center",
        insurance: "Medicare",
        DXCodes: 3,
        CPTCodes: 2,
        status: CODINGREVIEWSTATUS.RFR,
    },
    {
        chartId: "CHART023",
        firstName: "Harper",
        lastName: "Wright",
        dos: "02-23-2024",
        pcp: "Dr. Alexander Moore",
        facility: "Cleveland Clinic",
        insurance: "Anthem",
        DXCodes: 4,
        CPTCodes: 5,
        status: CODINGREVIEWSTATUS.ACTIVE,
    },
    {
        chartId: "CHART024",
        firstName: "Daniel",
        lastName: "Scott",
        dos: "02-24-2024",
        pcp: "Dr. Emily Turner",
        facility: "Johns Hopkins Hospital",
        insurance: "Kaiser Permanente",
        DXCodes: 5,
        CPTCodes: 3,
        status: CODINGREVIEWSTATUS.RFR,
    },
    {
        chartId: "CHART025",
        firstName: "Ella",
        lastName: "Torres",
        dos: "02-25-2024",
        pcp: "Dr. Joshua Thomas",
        facility: "NewYork-Presbyterian Hospital",
        insurance: "Cigna",
        DXCodes: 2,
        CPTCodes: 1,
        status: CODINGREVIEWSTATUS.ACTIVE,
    },

];

/* coding Approve*/
export type CodingApprovedTypes = {
    chartId: string;
    firstName: string;
    lastName: string;
    dos: string; // Date of Service
    pcp: string; // Primary Care Physician
    facility: string;
    insurance: string;
    DXCodes: number;
    CPTCodes: number;
    ClaimNumber: number;
    status: CODINGAPPROVEDSTATUS
};

export const codingApprovedData: CodingApprovedTypes[] = [
    {
        chartId: "CHART001",
        firstName: "Michael",
        lastName: "Smith",
        dos: "02-01-2024",
        pcp: "Dr. Jennifer Brown",
        facility: "Mayo Clinic",
        insurance: "Cigna",
        DXCodes: 3,
        CPTCodes: 2,
        ClaimNumber: 1001,
        status: CODINGAPPROVEDSTATUS.PENDING,
    },
    {
        chartId: "CHART002",
        firstName: "Olivia",
        lastName: "Johnson",
        dos: "02-02-2024",
        pcp: "Dr. Robert Wilson",
        facility: "Cleveland Clinic",
        insurance: "Aetna",
        DXCodes: 5,
        CPTCodes: 4,
        ClaimNumber: 1002,
        status: CODINGAPPROVEDSTATUS.CREATED,
    },
    {
        chartId: "CHART003",
        firstName: "William",
        lastName: "Davis",
        dos: "02-03-2024",
        pcp: "Dr. Sophia Martinez",
        facility: "Johns Hopkins Hospital",
        insurance: "UnitedHealthcare",
        DXCodes: 2,
        CPTCodes: 3,
        ClaimNumber: 1003,
        status: CODINGAPPROVEDSTATUS.ERROR,
    },
    {
        chartId: "CHART004",
        firstName: "Sophia",
        lastName: "Garcia",
        dos: "02-04-2024",
        pcp: "Dr. Daniel Anderson",
        facility: "Massachusetts General Hospital",
        insurance: "Medicaid",
        DXCodes: 6,
        CPTCodes: 5,
        ClaimNumber: 1004,
        status: CODINGAPPROVEDSTATUS.CREATED,
    },
    {
        chartId: "CHART005",
        firstName: "James",
        lastName: "Miller",
        dos: "02-05-2024",
        pcp: "Dr. Emma Harris",
        facility: "Cedars-Sinai Medical Center",
        insurance: "Blue Cross Blue Shield",
        DXCodes: 4,
        CPTCodes: 1,
        ClaimNumber: 1005,
        status: CODINGAPPROVEDSTATUS.PENDING,
    },
    {
        chartId: "CHART006",
        firstName: "Isabella",
        lastName: "Rodriguez",
        dos: "02-06-2024",
        pcp: "Dr. Benjamin Lewis",
        facility: "Stanford Health Care",
        insurance: "Humana",
        DXCodes: 3,
        CPTCodes: 2,
        ClaimNumber: 1006,
        status: CODINGAPPROVEDSTATUS.ERROR,
    },
    {
        chartId: "CHART007",
        firstName: "Ethan",
        lastName: "Martinez",
        dos: "02-07-2024",
        pcp: "Dr. Abigail Clark",
        facility: "Mount Sinai Hospital",
        insurance: "Kaiser Permanente",
        DXCodes: 5,
        CPTCodes: 3,
        ClaimNumber: 1007,
        status: CODINGAPPROVEDSTATUS.CREATED,
    },
    {
        chartId: "CHART008",
        firstName: "Mia",
        lastName: "Lopez",
        dos: "02-08-2024",
        pcp: "Dr. Matthew Walker",
        facility: "NewYork-Presbyterian Hospital",
        insurance: "Anthem",
        DXCodes: 2,
        CPTCodes: 4,
        ClaimNumber: 1008,
        status: CODINGAPPROVEDSTATUS.PENDING,
    },
    {
        chartId: "CHART009",
        firstName: "Alexander",
        lastName: "Gonzalez",
        dos: "02-09-2024",
        pcp: "Dr. Hannah Adams",
        facility: "UCLA Medical Center",
        insurance: "Cigna",
        DXCodes: 4,
        CPTCodes: 5,
        ClaimNumber: 1009,
        status: CODINGAPPROVEDSTATUS.ERROR,
    },
    {
        chartId: "CHART010",
        firstName: "Charlotte",
        lastName: "Wilson",
        dos: "02-10-2024",
        pcp: "Dr. Christopher King",
        facility: "Baylor University Medical Center",
        insurance: "Medicare",
        DXCodes: 6,
        CPTCodes: 3,
        ClaimNumber: 1010,
        status: CODINGAPPROVEDSTATUS.CREATED,
    },
    {
        chartId: "CHART011",
        firstName: "Daniel",
        lastName: "Perez",
        dos: "02-11-2024",
        pcp: "Dr. Natalie White",
        facility: "Cleveland Clinic",
        insurance: "UnitedHealthcare",
        DXCodes: 2,
        CPTCodes: 1,
        ClaimNumber: 1011,
        status: CODINGAPPROVEDSTATUS.PENDING,
    },
    {
        chartId: "CHART012",
        firstName: "Ava",
        lastName: "Harris",
        dos: "02-12-2024",
        pcp: "Dr. William Scott",
        facility: "Johns Hopkins Hospital",
        insurance: "Aetna",
        DXCodes: 5,
        CPTCodes: 4,
        ClaimNumber: 1012,
        status: CODINGAPPROVEDSTATUS.ERROR,
    },
    {
        chartId: "CHART013",
        firstName: "Logan",
        lastName: "Sanchez",
        dos: "02-13-2024",
        pcp: "Dr. Jessica Nelson",
        facility: "Cedars-Sinai Medical Center",
        insurance: "Medicaid",
        DXCodes: 3,
        CPTCodes: 2,
        ClaimNumber: 1013,
        status: CODINGAPPROVEDSTATUS.CREATED,
    },
    {
        chartId: "CHART014",
        firstName: "Emma",
        lastName: "Wright",
        dos: "02-14-2024",
        pcp: "Dr. Lucas Mitchell",
        facility: "Massachusetts General Hospital",
        insurance: "Humana",
        DXCodes: 6,
        CPTCodes: 3,
        ClaimNumber: 1014,
        status: CODINGAPPROVEDSTATUS.PENDING,
    },
    {
        chartId: "CHART015",
        firstName: "Noah",
        lastName: "Allen",
        dos: "02-15-2024",
        pcp: "Dr. Rachel Turner",
        facility: "Mount Sinai Hospital",
        insurance: "Kaiser Permanente",
        DXCodes: 4,
        CPTCodes: 5,
        ClaimNumber: 1015,
        status: CODINGAPPROVEDSTATUS.ERROR,
    },
    {
        chartId: "CHART016",
        firstName: "Liam",
        lastName: "Young",
        dos: "02-16-2024",
        pcp: "Dr. Nathan Rivera",
        facility: "NewYork-Presbyterian Hospital",
        insurance: "Anthem",
        DXCodes: 5,
        CPTCodes: 2,
        ClaimNumber: 1016,
        status: CODINGAPPROVEDSTATUS.CREATED,
    },
    {
        chartId: "CHART017",
        firstName: "Sophia",
        lastName: "Torres",
        dos: "02-17-2024",
        pcp: "Dr. Ethan Carter",
        facility: "UCLA Medical Center",
        insurance: "Cigna",
        DXCodes: 2,
        CPTCodes: 4,
        ClaimNumber: 1017,
        status: CODINGAPPROVEDSTATUS.PENDING,
    },
    {
        chartId: "CHART018",
        firstName: "Lucas",
        lastName: "Baker",
        dos: "02-18-2024",
        pcp: "Dr. Emily Foster",
        facility: "Baylor University Medical Center",
        insurance: "Medicare",
        DXCodes: 6,
        CPTCodes: 3,
        ClaimNumber: 1018,
        status: CODINGAPPROVEDSTATUS.ERROR,
    },
    {
        chartId: "CHART019",
        firstName: "Grace",
        lastName: "Hill",
        dos: "02-19-2024",
        pcp: "Dr. Alexander Bennett",
        facility: "Stanford Health Care",
        insurance: "UnitedHealthcare",
        DXCodes: 3,
        CPTCodes: 5,
        ClaimNumber: 1019,
        status: CODINGAPPROVEDSTATUS.CREATED,
    },
    {
        chartId: "CHART020",
        firstName: "Mason",
        lastName: "Nelson",
        dos: "02-20-2024",
        pcp: "Dr. Victoria Cooper",
        facility: "Mayo Clinic",
        insurance: "Aetna",
        DXCodes: 5,
        CPTCodes: 1,
        ClaimNumber: 1020,
        status: CODINGAPPROVEDSTATUS.PENDING,
    },
];



/* Claim number */
/* DraftData */
export type DraftDataTypes = {
    chartId: string;
    appId?: string;
    mID?: string;
    dos: string; // Date of Service
    memberId: string;
    firstName: string;
    lastName: string;
    dob: string; // Date of Birth
    pcp: string; // Primary Care Physician
    facility: string;
    insurance: string;
    status: DRAFTSTATUS;
    assignTo: string;
};

export const DraftData: DraftDataTypes[] = [
    {
        chartId: "CH12345",
        dos: "04-08-2025",
        memberId: "M001",
        firstName: "John",
        lastName: "Doe",
        dob: "04-08-1990",
        pcp: "Dr. Smith",
        facility: "ABC Clinic",
        insurance: "Blue Shield",
        status: DRAFTSTATUS.PROCESSING,
        assignTo: "Admin1",
    },
    {
        chartId: "CH12346",
        dos: "04-07-2025",
        memberId: "M002",
        firstName: "Jane",
        lastName: "Doe",
        dob: "08-21-1985",
        pcp: "Dr. Williams",
        facility: "XYZ Hospital",
        insurance: "United Health",
        status: DRAFTSTATUS.QUEUE,
        assignTo: "Admin2",
    },
    {
        chartId: "CH12347",
        dos: "02-05-2024",
        memberId: "M003",
        firstName: "Alice",
        lastName: "Brown",
        dob: "02-10-1993",
        pcp: "Dr. Carter",
        facility: "DEF Clinic",
        insurance: "Aetna",
        status: DRAFTSTATUS.ERROR,
        assignTo: "Admin3",
    },
    {
        chartId: "CH12348",
        dos: "02-10-2024",
        memberId: "M004",
        firstName: "Bob",
        lastName: "Smith",
        dob: "07-19-1988",
        pcp: "Dr. Jones",
        facility: "LMN Health Center",
        insurance: "Cigna",
        status: DRAFTSTATUS.PROCESSING,
        assignTo: "Admin4",
    },
    {
        chartId: "CH12349",
        dos: "03-03-2024",
        memberId: "M005",
        firstName: "Charlie",
        lastName: "Davis",
        dob: "04-11-1992",
        pcp: "Dr. Adams",
        facility: "OPQ Medical",
        insurance: "Blue Shield",
        status: DRAFTSTATUS.QUEUE,
        assignTo: "Admin1",
    },
    {
        chartId: "CH12350",
        dos: "03-15-2024",
        memberId: "M006",
        firstName: "David",
        lastName: "Clark",
        dob: "06-30-1980",
        pcp: "Dr. Scott",
        facility: "RST Hospital",
        insurance: "United Health",
        status: DRAFTSTATUS.ERROR,
        assignTo: "Admin2",
    },
    {
        chartId: "CH12351",
        dos: "04-05-2024",
        memberId: "M007",
        firstName: "Eve",
        lastName: "Wilson",
        dob: "11-25-1995",
        pcp: "Dr. Lewis",
        facility: "XYZ Health",
        insurance: "Aetna",
        status: DRAFTSTATUS.PROCESSING,
        assignTo: "Admin3",
    },
    {
        chartId: "CH12352",
        dos: "04-10-2024",
        memberId: "M008",
        firstName: "Frank",
        lastName: "Miller",
        dob: "12-18-1977",
        pcp: "Dr. Hall",
        facility: "QRS Clinic",
        insurance: "Cigna",
        status: DRAFTSTATUS.QUEUE,
        assignTo: "Admin4",
    },
    {
        chartId: "CH12353",
        dos: "05-01-2024",
        memberId: "M009",
        firstName: "Grace",
        lastName: "White",
        dob: "03-09-1991",
        pcp: "Dr. Thompson",
        facility: "LMN Hospital",
        insurance: "Blue Shield",
        status: DRAFTSTATUS.ERROR,
        assignTo: "Admin1",
    },
    {
        chartId: "CH12354",
        dos: "05-15-2024",
        memberId: "M010",
        firstName: "Henry",
        lastName: "Moore",
        dob: "09-22-1983",
        pcp: "Dr. Lopez",
        facility: "ABC Health",
        insurance: "United Health",
        status: DRAFTSTATUS.PROCESSING,
        assignTo: "Admin2",
    },
    {
        chartId: "CH12355",
        dos: "06-01-2024",
        memberId: "M011",
        firstName: "Ivy",
        lastName: "Anderson",
        dob: "07-05-1997",
        pcp: "Dr. Nelson",
        facility: "XYZ Clinic",
        insurance: "Aetna",
        status: DRAFTSTATUS.QUEUE,
        assignTo: "Admin3",
    },
    {
        chartId: "CH12356",
        dos: "06-20-2024",
        memberId: "M012",
        firstName: "Jack",
        lastName: "Thomas",
        dob: "10-10-1986",
        pcp: "Dr. Wright",
        facility: "DEF Medical",
        insurance: "Cigna",
        status: DRAFTSTATUS.ERROR,
        assignTo: "Admin4",
    },
    {
        chartId: "CH12357",
        dos: "07-10-2024",
        memberId: "M013",
        firstName: "Kelly",
        lastName: "Taylor",
        dob: "01-14-1994",
        pcp: "Dr. King",
        facility: "QRS Hospital",
        insurance: "Blue Shield",
        status: DRAFTSTATUS.PROCESSING,
        assignTo: "Admin1",
    },
    {
        chartId: "CH12358",
        dos: "07-25-2024",
        memberId: "M014",
        firstName: "Liam",
        lastName: "Harris",
        dob: "12-30-1989",
        pcp: "Dr. Martinez",
        facility: "RST Health",
        insurance: "United Health",
        status: DRAFTSTATUS.QUEUE,
        assignTo: "Admin2",
    },
    {
        chartId: "CH12359",
        dos: "08-05-2024",
        memberId: "M015",
        firstName: "Mia",
        lastName: "Young",
        dob: "06-21-1990",
        pcp: "Dr. Allen",
        facility: "LMN Clinic",
        insurance: "Aetna",
        status: DRAFTSTATUS.ERROR,
        assignTo: "Admin3",
    },
    {
        chartId: "CH12360",
        dos: "08-20-2024",
        memberId: "M016",
        firstName: "Nathan",
        lastName: "Lee",
        dob: "03-17-1982",
        pcp: "Dr. Perez",
        facility: "OPQ Hospital",
        insurance: "Cigna",
        status: DRAFTSTATUS.PROCESSING,
        assignTo: "Admin4",
    },
    {
        chartId: "CH12361",
        dos: "09-01-2024",
        memberId: "M017",
        firstName: "Olivia",
        lastName: "Martin",
        dob: "02-25-1996",
        pcp: "Dr. Kim",
        facility: "QRS Medical",
        insurance: "Blue Shield",
        status: DRAFTSTATUS.QUEUE,
        assignTo: "Admin1",
    },
    {
        chartId: "CH12362",
        dos: "09-10-2024",
        memberId: "M018",
        firstName: "Paul",
        lastName: "Jackson",
        dob: "05-30-1989",
        pcp: "Dr. Stevens",
        facility: "DEF Clinic",
        insurance: "United Health",
        status: DRAFTSTATUS.ERROR,
        assignTo: "Admin2",
    },
    {
        chartId: "CH12363",
        dos: "09-15-2024",
        memberId: "M019",
        firstName: "Quinn",
        lastName: "Wright",
        dob: "11-12-1992",
        pcp: "Dr. Walker",
        facility: "XYZ Health",
        insurance: "Aetna",
        status: DRAFTSTATUS.PROCESSING,
        assignTo: "Admin3",
    },
    {
        chartId: "CH12364",
        dos: "10-01-2024",
        memberId: "M020",
        firstName: "Riley",
        lastName: "Roberts",
        dob: "08-14-1980",
        pcp: "Dr. Foster",
        facility: "ABC Health",
        insurance: "Cigna",
        status: DRAFTSTATUS.QUEUE,
        assignTo: "Admin4",
    },
    {
        chartId: "CH12365",
        dos: "10-15-2024",
        memberId: "M021",
        firstName: "Sophia",
        lastName: "Green",
        dob: "04-28-1993",
        pcp: "Dr. Bell",
        facility: "QRS Medical",
        insurance: "Blue Shield",
        status: DRAFTSTATUS.ERROR,
        assignTo: "Admin1",
    },
    {
        chartId: "CH12366",
        dos: "11-01-2024",
        memberId: "M022",
        firstName: "Thomas",
        lastName: "Hernandez",
        dob: "07-19-1985",
        pcp: "Dr. Mitchell",
        facility: "RST Clinic",
        insurance: "United Health",
        status: DRAFTSTATUS.PROCESSING,
        assignTo: "Admin2",
    }
];

/* review */
export type ReviewDataTypes = {
    chartId: string;
    mID?: string;
    appId?: string,
    dos: string; // Date of Service
    memberId: string;
    firstName: string;
    lastName: string;
    dob: string; // Date of Birth
    pcp: string; // Primary Care Physician
    facility: string;
    insurance: string;
    status: REVIEWSTATUS;
    assignTo: string;
    newSuggestion: number;
    carryForward: number
};

export const ReviewData: ReviewDataTypes[] = [
    {
        chartId: "CH001",
        dos: "03-15-2024",
        memberId: "M001",
        firstName: "John",
        lastName: "Doe",
        dob: "06-25-1985",
        pcp: "Dr. Smith",
        facility: "General Hospital",
        insurance: "HealthCare Plus",
        status: REVIEWSTATUS.INPROGRESS,
        assignTo: "Reviewer A",
        newSuggestion: 3,
        carryForward: 1
    },
    {
        chartId: "CH002",
        dos: "02-10-2024",
        memberId: "M002",
        firstName: "Jane",
        lastName: "Smith",
        dob: "08-12-1990",
        pcp: "Dr. Brown",
        facility: "City Clinic",
        insurance: "Wellness Cover",
        status: REVIEWSTATUS.RFR,
        assignTo: "Reviewer B",
        newSuggestion: 2,
        carryForward: 0
    },
    {
        chartId: "CH003",
        dos: "04-05-2024",
        memberId: "M003",
        firstName: "Alice",
        lastName: "Johnson",
        dob: "03-30-1982",
        pcp: "Dr. Green",
        facility: "Sunrise Health",
        insurance: "MediSure",
        status: REVIEWSTATUS.HOLD,
        assignTo: "Reviewer C",
        newSuggestion: 1,
        carryForward: 2
    },
    {
        chartId: "CH004",
        dos: "01-20-2024",
        memberId: "M004",
        firstName: "Michael",
        lastName: "Williams",
        dob: "11-05-1978",
        pcp: "Dr. Adams",
        facility: "Downtown Clinic",
        insurance: "Care First",
        status: REVIEWSTATUS.ADDITIONAL,
        assignTo: "Reviewer D",
        newSuggestion: 4,
        carryForward: 1
    },
    {
        chartId: "CH005",
        dos: "05-12-2024",
        memberId: "M005",
        firstName: "Emily",
        lastName: "Davis",
        dob: "07-14-1992",
        pcp: "Dr. Taylor",
        facility: "Community Health",
        insurance: "Prime Care",
        status: REVIEWSTATUS.DOCUMENT,
        assignTo: "Reviewer E",
        newSuggestion: 0,
        carryForward: 3
    },
    {
        chartId: "CH006",
        dos: "06-08-2024",
        memberId: "M006",
        firstName: "Robert",
        lastName: "Miller",
        dob: "02-19-1987",
        pcp: "Dr. Lee",
        facility: "Wellness Hospital",
        insurance: "MediPlus",
        status: REVIEWSTATUS.INPROGRESS,
        assignTo: "Reviewer F",
        newSuggestion: 3,
        carryForward: 1
    },
    {
        chartId: "CH007",
        dos: "07-25-2024",
        memberId: "M007",
        firstName: "Sophia",
        lastName: "Wilson",
        dob: "09-23-1995",
        pcp: "Dr. Martinez",
        facility: "CarePoint",
        insurance: "HealthFirst",
        status: REVIEWSTATUS.RFR,
        assignTo: "Reviewer G",
        newSuggestion: 2,
        carryForward: 0
    },
    {
        chartId: "CH008",
        dos: "08-30-2024",
        memberId: "M008",
        firstName: "David",
        lastName: "Anderson",
        dob: "04-10-1980",
        pcp: "Dr. Robinson",
        facility: "Sunset Medical",
        insurance: "Secure Health",
        status: REVIEWSTATUS.HOLD,
        assignTo: "Reviewer H",
        newSuggestion: 1,
        carryForward: 2
    },
    {
        chartId: "CH009",
        dos: "09-15-2024",
        memberId: "M009",
        firstName: "Olivia",
        lastName: "Thomas",
        dob: "12-01-1988",
        pcp: "Dr. White",
        facility: "Eastside Clinic",
        insurance: "CareShield",
        status: REVIEWSTATUS.ADDITIONAL,
        assignTo: "Reviewer I",
        newSuggestion: 4,
        carryForward: 1
    },
    {
        chartId: "CH010",
        dos: "10-22-2024",
        memberId: "M010",
        firstName: "Daniel",
        lastName: "Moore",
        dob: "05-08-1993",
        pcp: "Dr. Hall",
        facility: "Metro Medical",
        insurance: "BlueCare",
        status: REVIEWSTATUS.DOCUMENT,
        assignTo: "Reviewer J",
        newSuggestion: 0,
        carryForward: 3
    },
    {
        chartId: "CH011",
        dos: "11-10-2024",
        memberId: "M011",
        firstName: "Ethan",
        lastName: "Harris",
        dob: "07-15-1986",
        pcp: "Dr. Nelson",
        facility: "Greenwood Hospital",
        insurance: "WellCare",
        status: REVIEWSTATUS.INPROGRESS,
        assignTo: "Reviewer K",
        newSuggestion: 2,
        carryForward: 1
    },
    {
        chartId: "CH012",
        dos: "12-05-2024",
        memberId: "M012",
        firstName: "Ava",
        lastName: "Clark",
        dob: "10-30-1990",
        pcp: "Dr. Carter",
        facility: "Sunrise Clinic",
        insurance: "HealthTrust",
        status: REVIEWSTATUS.RFR,
        assignTo: "Reviewer L",
        newSuggestion: 3,
        carryForward: 0
    },
    {
        chartId: "CH013",
        dos: "01-18-2025",
        memberId: "M013",
        firstName: "Liam",
        lastName: "Lewis",
        dob: "03-05-1984",
        pcp: "Dr. Parker",
        facility: "Metro Medical Center",
        insurance: "SecureHealth",
        status: REVIEWSTATUS.HOLD,
        assignTo: "Reviewer M",
        newSuggestion: 1,
        carryForward: 2
    },
    {
        chartId: "CH014",
        dos: "02-20-2025",
        memberId: "M014",
        firstName: "Mia",
        lastName: "Walker",
        dob: "06-18-1993",
        pcp: "Dr. Murphy",
        facility: "Community Health",
        insurance: "CareShield",
        status: REVIEWSTATUS.ADDITIONAL,
        assignTo: "Reviewer N",
        newSuggestion: 4,
        carryForward: 1
    },
    {
        chartId: "CH015",
        dos: "03-15-2025",
        memberId: "M015",
        firstName: "Noah",
        lastName: "Hall",
        dob: "08-22-1979",
        pcp: "Dr. Mitchell",
        facility: "Sunset Health Center",
        insurance: "BlueCare",
        status: REVIEWSTATUS.DOCUMENT,
        assignTo: "Reviewer O",
        newSuggestion: 0,
        carryForward: 3
    },
    {
        chartId: "CH016",
        dos: "04-10-2025",
        memberId: "M016",
        firstName: "Charlotte",
        lastName: "Young",
        dob: "05-09-1988",
        pcp: "Dr. Martinez",
        facility: "Westside Clinic",
        insurance: "MediPlus",
        status: REVIEWSTATUS.INPROGRESS,
        assignTo: "Reviewer P",
        newSuggestion: 3,
        carryForward: 1
    },
    {
        chartId: "CH017",
        dos: "05-22-2025",
        memberId: "M017",
        firstName: "James",
        lastName: "King",
        dob: "09-14-1985",
        pcp: "Dr. Thompson",
        facility: "CarePoint Medical",
        insurance: "HealthFirst",
        status: REVIEWSTATUS.RFR,
        assignTo: "Reviewer Q",
        newSuggestion: 2,
        carryForward: 0
    },
    {
        chartId: "CH018",
        dos: "06-08-2025",
        memberId: "M018",
        firstName: "Isabella",
        lastName: "Scott",
        dob: "12-02-1992",
        pcp: "Dr. Roberts",
        facility: "Metro Healthcare",
        insurance: "WellCare",
        status: REVIEWSTATUS.HOLD,
        assignTo: "Reviewer R",
        newSuggestion: 1,
        carryForward: 2
    },
    {
        chartId: "CH019",
        dos: "07-30-2025",
        memberId: "M019",
        firstName: "Benjamin",
        lastName: "Lopez",
        dob: "11-25-1983",
        pcp: "Dr. Evans",
        facility: "Downtown Medical Center",
        insurance: "CareTrust",
        status: REVIEWSTATUS.ADDITIONAL,
        assignTo: "Reviewer S",
        newSuggestion: 4,
        carryForward: 1
    },
    {
        chartId: "CH020",
        dos: "08-19-2025",
        memberId: "M020",
        firstName: "Harper",
        lastName: "White",
        dob: "04-11-1996",
        pcp: "Dr. Brooks",
        facility: "General Hospital",
        insurance: "MediCare",
        status: REVIEWSTATUS.DOCUMENT,
        assignTo: "Reviewer T",
        newSuggestion: 0,
        carryForward: 3
    }
];


/* Provider review */
export type ProviderReviewDataTypes = {
    chartId: string;
    mID?: string;
    appId?: string;
    dos: string; // Date of Service
    memberId: string;
    firstName: string;
    lastName: string;
    dob: string; // Date of Birth
    pcp: string; // Primary Care Physician
    facility: string;
    insurance: string;
    status: REVIEWSTATUS;
    assignTo: string;
    newSuggestion: number;
    carryForward: number
};

export const ProviderReviewData: ProviderReviewDataTypes[] = [
    {
        chartId: "CH10001",
        dos: "01-10-2024",
        memberId: "M101",
        firstName: "Alice",
        lastName: "Johnson",
        dob: "03-15-1985",
        pcp: "Dr. Smith",
        facility: "ABC Medical Center",
        insurance: "Aetna",
        status: REVIEWSTATUS.RFR,
        assignTo: "Admin1",
        newSuggestion: 17,
        carryForward: 2,
    },
    {
        chartId: "CH10002",
        dos: "01-15-2024",
        memberId: "M102",
        firstName: "Bob",
        lastName: "Anderson",
        dob: "07-22-1978",
        pcp: "Dr. Roberts",
        facility: "XYZ Hospital",
        insurance: "Blue Shield",
        status: REVIEWSTATUS.INPROGRESS,
        assignTo: "Admin2",
        newSuggestion: 2,
        carryForward: 16,
    },
    {
        chartId: "CH10003",
        dos: "02-01-2024",
        memberId: "M103",
        firstName: "Charlie",
        lastName: "Brown",
        dob: "06-10-1990",
        pcp: "Dr. Miller",
        facility: "Wellness Clinic",
        insurance: "Cigna",
        status: REVIEWSTATUS.HOLD,
        assignTo: "Admin3",
        newSuggestion: 16,
        carryForward: 10,
    },
    {
        chartId: "CH10004",
        dos: "02-10-2024",
        memberId: "M104",
        firstName: "David",
        lastName: "Clark",
        dob: "12-25-1982",
        pcp: "Dr. Thomas",
        facility: "Health Center A",
        insurance: "United Health",
        status: REVIEWSTATUS.ADDITIONAL,
        assignTo: "Admin4",
        newSuggestion: 8,
        carryForward: 3,
    },
    {
        chartId: "CH10005",
        dos: "02-20-2024",
        memberId: "M105",
        firstName: "Emma",
        lastName: "Wilson",
        dob: "05-30-1993",
        pcp: "Dr. Scott",
        facility: "Care Hospital",
        insurance: "Aetna",
        status: REVIEWSTATUS.DOCUMENT,
        assignTo: "Admin1",
        newSuggestion: 19,
        carryForward: 30,
    },
    {
        chartId: "CH10006",
        dos: "03-05-2024",
        memberId: "M106",
        firstName: "Frank",
        lastName: "Morris",
        dob: "10-18-1975",
        pcp: "Dr. Hall",
        facility: "General Health Clinic",
        insurance: "Blue Shield",
        status: REVIEWSTATUS.RFR,
        assignTo: "Admin2",
        newSuggestion: 6,
        carryForward: 13,
    },
    {
        chartId: "CH10007",
        dos: "03-15-2024",
        memberId: "M107",
        firstName: "Grace",
        lastName: "Bennett",
        dob: "08-05-1988",
        pcp: "Dr. White",
        facility: "Health & Wellness Center",
        insurance: "Cigna",
        status: REVIEWSTATUS.INPROGRESS,
        assignTo: "Admin3",
        newSuggestion: 26,
        carryForward: 19,
    },
    {
        chartId: "CH10008",
        dos: "03-25-2024",
        memberId: "M108",
        firstName: "Henry",
        lastName: "Evans",
        dob: "03-14-1981",
        pcp: "Dr. Adams",
        facility: "MedCare Hospital",
        insurance: "United Health",
        status: REVIEWSTATUS.HOLD,
        assignTo: "Admin4",
        newSuggestion: 4,
        carryForward: 20,
    },
    {
        chartId: "CH10009",
        dos: "04-05-2024",
        memberId: "M109",
        firstName: "Isabel",
        lastName: "Green",
        dob: "06-21-1992",
        pcp: "Dr. Martinez",
        facility: "ABC Medical Center",
        insurance: "Aetna",
        status: REVIEWSTATUS.ADDITIONAL,
        assignTo: "Admin1",
        newSuggestion: 18,
        carryForward: 18,
    },
    {
        chartId: "CH10010",
        dos: "04-10-2024",
        memberId: "M110",
        firstName: "Jack",
        lastName: "Patterson",
        dob: "09-30-1983",
        pcp: "Dr. Carter",
        facility: "XYZ Hospital",
        insurance: "Blue Shield",
        status: REVIEWSTATUS.DOCUMENT,
        assignTo: "Admin2",
        newSuggestion: 16,
        carryForward: 18,
    },
    {
        chartId: "CH10011",
        dos: "04-20-2024",
        memberId: "M111",
        firstName: "Kelly",
        lastName: "Morgan",
        dob: "11-22-1991",
        pcp: "Dr. Lewis",
        facility: "Wellness Clinic",
        insurance: "Cigna",
        status: REVIEWSTATUS.RFR,
        assignTo: "Admin3",
        newSuggestion: 28,
        carryForward: 27,
    },
    {
        chartId: "CH10012",
        dos: "05-01-2024",
        memberId: "M112",
        firstName: "Liam",
        lastName: "Turner",
        dob: "07-17-1979",
        pcp: "Dr. Hall",
        facility: "Health Center A",
        insurance: "United Health",
        status: REVIEWSTATUS.INPROGRESS,
        assignTo: "Admin4",
        newSuggestion: 15,
        carryForward: 30,
    },
    {
        chartId: "CH10013",
        dos: "05-10-2024",
        memberId: "M113",
        firstName: "Mia",
        lastName: "Harrison",
        dob: "04-29-1986",
        pcp: "Dr. Scott",
        facility: "Care Hospital",
        insurance: "Aetna",
        status: REVIEWSTATUS.HOLD,
        assignTo: "Admin1",
        newSuggestion: 6,
        carryForward: 20,
    },
    {
        chartId: "CH10014",
        dos: "05-20-2024",
        memberId: "M114",
        firstName: "Nathan",
        lastName: "Perry",
        dob: "02-12-1994",
        pcp: "Dr. Thomas",
        facility: "General Health Clinic",
        insurance: "Blue Shield",
        status: REVIEWSTATUS.ADDITIONAL,
        assignTo: "Admin2",
        newSuggestion: 6,
        carryForward: 17,
    },
    {
        chartId: "CH10015",
        dos: "05-25-2024",
        memberId: "M115",
        firstName: "Olivia",
        lastName: "Reed",
        dob: "05-07-1980",
        pcp: "Dr. White",
        facility: "Health & Wellness Center",
        insurance: "Cigna",
        status: REVIEWSTATUS.DOCUMENT,
        assignTo: "Admin3",
        newSuggestion: 11,
        carryForward: 8,
    }
];

/* individual provider type */
/* Pending Data */
export type ProviderType = {
    chartId: string;
    dos: string; // Date of Service
    pcp: string; // Primary Care Physician
    facility: string;
    insurance: string;
    newSugg: number;
    carryForward: number;
};

export const ProviderData: ProviderType[] = [
    {
        chartId: "CHT001",
        dos: "02-01-2024",
        pcp: "Dr. John Doe",
        facility: "General Hospital",
        insurance: "HealthCare Plus",
        newSugg: 5,
        carryForward: 2,
    },
    {
        chartId: "CHT002",
        dos: "02-02-2024",
        pcp: "Dr. Jane Smith",
        facility: "City Medical Center",
        insurance: "MediSecure",
        newSugg: 3,
        carryForward: 1,
    },
    {
        chartId: "CHT003",
        dos: "02-03-2024",
        pcp: "Dr. Emily Johnson",
        facility: "Sunrise Clinic",
        insurance: "WellnessCare",
        newSugg: 4,
        carryForward: 0,
    },
    {
        chartId: "CHT004",
        dos: "02-04-2024",
        pcp: "Dr. Michael Brown",
        facility: "Downtown Health",
        insurance: "SafeHealth",
        newSugg: 2,
        carryForward: 3,
    },
    {
        chartId: "CHT005",
        dos: "02-05-2024",
        pcp: "Dr. Olivia Wilson",
        facility: "Metro Hospital",
        insurance: "PrimeCare",
        newSugg: 6,
        carryForward: 2,
    },
    {
        chartId: "CHT006",
        dos: "02-06-2024",
        pcp: "Dr. William Davis",
        facility: "Northside Clinic",
        insurance: "LifeShield",
        newSugg: 3,
        carryForward: 4,
    },
    {
        chartId: "CHT007",
        dos: "02-07-2024",
        pcp: "Dr. Sophia Martinez",
        facility: "Eastview Health",
        insurance: "CareFirst",
        newSugg: 7,
        carryForward: 1,
    },
    {
        chartId: "CHT008",
        dos: "02-08-2024",
        pcp: "Dr. James Anderson",
        facility: "Westend Medical",
        insurance: "WellCare",
        newSugg: 2,
        carryForward: 0,
    },
    {
        chartId: "CHT009",
        dos: "02-09-2024",
        pcp: "Dr. Ava Thomas",
        facility: "Horizon Health",
        insurance: "MediPlus",
        newSugg: 5,
        carryForward: 3,
    },
    {
        chartId: "CHT010",
        dos: "02-10-2024",
        pcp: "Dr. Benjamin Lee",
        facility: "Central Hospital",
        insurance: "HealthGuard",
        newSugg: 4,
        carryForward: 2,
    },
    {
        chartId: "CHT011",
        dos: "02-11-2024",
        pcp: "Dr. Charlotte White",
        facility: "Evergreen Care",
        insurance: "MediHealth",
        newSugg: 3,
        carryForward: 1,
    },
    {
        chartId: "CHT012",
        dos: "02-12-2024",
        pcp: "Dr. Daniel Wilson",
        facility: "Lakeside Medical",
        insurance: "WellLife",
        newSugg: 6,
        carryForward: 0,
    },
    {
        chartId: "CHT013",
        dos: "02-13-2024",
        pcp: "Dr. Sophia Carter",
        facility: "Highland Hospital",
        insurance: "LifeCare",
        newSugg: 4,
        carryForward: 2,
    },
    {
        chartId: "CHT014",
        dos: "02-14-2024",
        pcp: "Dr. Ethan Johnson",
        facility: "Midtown Clinic",
        insurance: "HealthSecure",
        newSugg: 5,
        carryForward: 3,
    },
    {
        chartId: "CHT015",
        dos: "02-15-2024",
        pcp: "Dr. Lily Adams",
        facility: "Bayview Health",
        insurance: "PrimeCare",
        newSugg: 7,
        carryForward: 2,
    },
    {
        chartId: "CHT016",
        dos: "02-16-2024",
        pcp: "Dr. Henry Brown",
        facility: "Westside Medical",
        insurance: "SafeHealth",
        newSugg: 2,
        carryForward: 4,
    },
    {
        chartId: "CHT017",
        dos: "02-17-2024",
        pcp: "Dr. Grace Parker",
        facility: "Riverside Clinic",
        insurance: "CareFirst",
        newSugg: 3,
        carryForward: 1,
    },
    {
        chartId: "CHT018",
        dos: "02-18-2024",
        pcp: "Dr. Lucas Evans",
        facility: "Northpoint Health",
        insurance: "MediSecure",
        newSugg: 6,
        carryForward: 0,
    },
    {
        chartId: "CHT019",
        dos: "02-19-2024",
        pcp: "Dr. Hannah Scott",
        facility: "Sunset Hospital",
        insurance: "LifeShield",
        newSugg: 5,
        carryForward: 3,
    },
    {
        chartId: "CHT020",
        dos: "02-20-2024",
        pcp: "Dr. Ryan Turner",
        facility: "Summit Medical",
        insurance: "HealthCare Plus",
        newSugg: 4,
        carryForward: 2,
    }
];





